import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    /**
     * Generated by the shadcn CLI and owned by it — `shadcn add` overwrites
     * these wholesale, so any hand-fix here is undone on the next run.
     *
     * Two rules fire on them today: `react-hooks/purity` on the `Math.random()`
     * width in `SidebarMenuSkeleton`, and `react-hooks/set-state-in-effect` in
     * `use-mobile`. The first is a genuine hydration hazard, which is a reason
     * not to render `SidebarMenuSkeleton` — and nothing here does. Our own code
     * that *uses* these primitives is linted normally; only the vendored files
     * are exempt.
     */
    "src/components/shadcn/**",
    "src/hooks/use-mobile.ts",
  ]),
]);

export default eslintConfig;
